name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Build Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.m2/repository
          key: build-cache

      - name: Build and Test
        run: |
          ./gradlew check assemble

      - name: Archive cli module test reports
          uses: actions/upload-artifact@v1
          with:
            name: test-reports
            path: /home/runner/work/blog-post-promoter/blog-post-promoter/cli/build/reports/tests

      - name: Publish Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dasnervtdoch/blog-post-promoter
          tags: latest
